AP-44 download binary
thecoderstudio/apollo-web pull request #11
Opened 2020-08-20 10:33 UTC by rikvanderwerf

## Code R Ticket
_Please provide a link to the Code R Jira ticket if applicable_

<https://partypeak.atlassian.net/browse/AP-44>

## Description
_Please give a description of the pull request._

## Dependencies
_Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests_

*

## Additional notes
_Anything else you want to mention._

2020-08-20 15:30 UTC, RobinSiep commented
Codacy comments are justified. It was seemingly moved out of draft regardless but I'll hold on reviewing until those are fixed since they should prompt some changes to the PR.

2020-08-24 10:36 UTC, RobinSiep commented
Codacy.

2020-09-18 13:27 UTC, RobinSiep commented
I don't know if you can reproduce but there seem to be some unintended graphical issues on this branch and the form won't work. `Create agent` button doesn't work) and dropdowns also don't update to their selected value until I reopen the modal. Could be something cached on my side so let me know if you have it too.

![image](https://user-images.githubusercontent.com/5303534/93602774-5fd5af80-f9c3-11ea-800d-b80b899ae5e3.png)
![image](https://user-images.githubusercontent.com/5303534/93602797-682dea80-f9c3-11ea-96bf-a9d1c4cc8460.png)
![image](https://user-images.githubusercontent.com/5303534/93602805-6ebc6200-f9c3-11ea-8b2d-c587a874afcb.png)


I'll start on my review but just thought I'd mention this already.

2020-09-18 13:41 UTC, RobinSiep commented
I don't have the graphical issues anymore and the button works now after re-switching branches so who knows but it seemed to be on my end :) 

The dropdowns do still not function properly for me however.

2020-09-21 08:37 UTC, RobinSiep requested changes

2020-09-21 08:37 UTC, robinsiep commented on package.json
> +    "babel-jest": "26.3",
I've commented this previously on the "change password" PR but I think the current policy should be to not pin minor versions. You can bump the minimum version required though.

2020-09-21 08:37 UTC, robinsiep commented on src/actions/add-agent.js
> +function selectOperatingSystem(operatingSystem) {
I don't really see the reason to involve Redux into this.

Is it to remember the selected value for next time the user creates an agent? This _could_ be appropriate but it's a choice between that and pre-selecting the most common OS and architecture.

2020-09-21 08:37 UTC, robinsiep commented on src/components/CopyToClipboard.jsx
> +  text-overflow: ellipsis;
Can we make this field horizontally scrollable instead? I think it's standard practice with these thing to be able to see and select the whole value if desired. It makes it easier to know / verify what you're copying.

2020-09-21 08:37 UTC, robinsiep commented on src/components/Input.jsx
>  import PropTypes from 'prop-types';
I'll wait to do a full review on this file until the other PR has been merged since it seems to contain some of the same changes.

2020-09-21 08:37 UTC, robinsiep commented on src/components/NavBar.jsx
> +  margin-left: 25px;
Maybe CSS grid gaps would be more appropiate?

2020-09-21 08:37 UTC, RobinSiep commented on src/components/modals/AddAgentModal.jsx
> +import React from 'react';
This file is too large, it isn't even rendered by Github by default. The reason it's this large is because this component is doing way too much. 

It's large enough that it's hard to initially recommend all that should be split / abstracted but I'd start with splitting the two different paths. I imagine once that's done a variety of possible improvements will become clear while keeping single responsibility and DRY in mind.

2020-09-21 08:37 UTC, RobinSiep commented on src/lib/NewAgentHandler.js
> +export default class NewAgentHandler {
I'm skipping this one due to the changes required in `AddAgentModel.jsx`

2020-09-21 08:37 UTC, RobinSiep commented on src/reducers/add-agent.js
> +import {
I guess my earlier question about the use of Redux applies here too.

2020-09-21 08:37 UTC, RobinSiep commented on src/reducers/root.js
> -  theme: themeReducer
Ideally we'd keep this alphabetically sorted.

2020-09-21 08:37 UTC, RobinSiep commented on src/validation/agent.js
> +    .max(100, "Max 100 charactes")
```suggestion
    .max(100, "Max 100 characters")
```

2020-09-21 08:37 UTC, RobinSiep commented on tests/App.test.jsx
> +      addAgent: {
The fact that you need to do this in `App.test.jsx` highlights why it's a bit strange to handle this globally.

2020-09-21 08:37 UTC, RobinSiep commented on tests/components/modals/AddAgentModal.test.jsx
> +import React from 'react';
I'm skipping this one due to the changes required in `AddAgentModel.jsx`

2020-09-21 08:37 UTC, RobinSiep commented on tests/lib/NewAgentHandler.test.jsx
> +import NewAgentHandler from '../../src/lib/NewAgentHandler';
I'm skipping this one due to the changes required in `AddAgentModel.jsx`

2020-09-21 08:37 UTC, RobinSiep commented on tests/reducers/root.test.js
>    expect(rootReducer(undefined, {})).toEqual({
This used to be alphabetically ordered too, to match its counterpart.

2020-09-21 08:37 UTC, RobinSiep commented on tests/components/Dropdown.test.jsx
> +import { selectArchitecture } from "../../src/actions/add-agent";
I don't think I'd include this action to test a generic dropdown. Can't you use a mock?

2020-09-21 08:37 UTC, RobinSiep commented on tests/components/Dropdown.test.jsx
> +import React from 'react';
Seemingly the dropdown doesn't work correctly (at least on my machine) so when that's resolved we should add a test for it since these apparently don't verify the functionality correctly.

2020-09-21 08:37 UTC, RobinSiep commented on tests/reducers/add-agent.test.js
> + it("should return false as initial state", () => {
Could you clarify this? I don't see an assertion whether it returns `false` as an initial state but instead it seems to be an object.

2020-09-22 08:13 UTC, rikvanderwerf commented on src/actions/add-agent.js
> +function selectOperatingSystem(operatingSystem) {
Nope, just me not 100% understanding when to use it :D

2020-09-28 08:47 UTC, RobinSiep commented
I thought I'd first mention the bugs I've found:
Manual upload creates a command like:
```
chmod +x apollo-agent.bin && ./apollo-agent.bin --agent-id=undefined --secret=undefined --host=localhost:1970
```

As you can see both `agent-id` and `secret` ended up undefined. Also `localhost:1970` seems hardcoded in the code but is subject to change on top of it being unlikely this port is reachable (and pretty much impossible that it's reachable through `localhost`).

"Directly on target machine" creates a command like:
```
curl http://localhost:1970/agent/download?target_os=linux&target_arch=amd64 && chmod +x apollo-agent.bin && ./apollo-agent.bin --agent-id=undefined --secret=undefined --host=localhost:1970
```

where again the `agent-id` and `secret` is undefined. `curl` also won't download anything here. You'd have to pipe into a file or use `--output` when using `curl`.

2020-09-28 08:53 UTC, RobinSiep commented
Then there's this UI errors like:
![image](https://user-images.githubusercontent.com/5303534/94410866-2b5ab400-0178-11eb-8241-70c027cc723a.png)

and on for example iPhone 5/SE:
![image](https://user-images.githubusercontent.com/5303534/94411075-6e1c8c00-0178-11eb-9bba-ac0da0484e1b.png)

as well as the navigation bar being huge width and creating the need for horizontal scrolling on mobile.

2020-10-02 11:41 UTC, rikvanderwerf commented
For the navigation bar i created https://partypeak.atlassian.net/browse/AP-62, because it is also already an issue currently on develop.

2020-10-02 12:48 UTC, RobinSiep commented
> For the navigation bar i created [partypeak.atlassian.net/browse/AP-62](https://partypeak.atlassian.net/browse/AP-62), because it is also already an issue currently on develop.

Develop is currently like this on the galaxy fold (worst case scenario, also reasonably unlikely) and scales well on the usual modern devices:
Fold:
<img width="187" alt="Screenshot 2020-10-02 at 14 41 22" src="https://user-images.githubusercontent.com/5303534/94924337-9d573400-04bd-11eb-9897-bf952143351b.png">

iPhone 6/7/8:
![image](https://user-images.githubusercontent.com/5303534/94924510-ec9d6480-04bd-11eb-815c-30766e21690c.png)



The current branch is like:
Fold:
<img width="185" alt="Screenshot 2020-10-02 at 14 42 27" src="https://user-images.githubusercontent.com/5303534/94924436-cf689600-04bd-11eb-8c65-6aebcac70df0.png">


iPhone 6/7/8:
<img width="219" alt="Screenshot 2020-10-02 at 14 44 07" src="https://user-images.githubusercontent.com/5303534/94924429-cb3c7880-04bd-11eb-8ff6-914e4d6f4572.png">

---
It's sure not great on develop and its responsiveness needs to be improved but I don't see a reason to make it worse on this branch, especially since it'll significantly impact the UX on the majority of devices.

2020-10-02 14:27 UTC, RobinSiep commented
> For the navigation bar i created partypeak.atlassian.net/browse/AP-62, because it is also already an issue currently on develop.

I don't know how far along this is, otherwise we could also block or something? It'd be a shame to have a scenario where we merge the navbar changes in their current state and it stays like that for an uncertain amount of time.

2020-10-05 08:33 UTC, rikvanderwerf commented
> I don't know how far along this is, otherwise we could also block or something? It'd be a shame to have a scenario where we merge the navbar changes in their current state and it stays like that for an uncertain amount of time.

Just reading this but already fixed it :)

2020-10-05 15:01 UTC, RobinSiep requested changes
If you have the modal open and scale to mobile the modal disappears until you open the nav menu.

---
There seems to be some CSS duplication and hidden coupling. Some of it might also be redundant but I find this very hard to judge in a PR.

What I've noticed at least is a fair amount of custom text styling and duplication of other things like shadow. As I said it's hard to judge but the CSS sometimes seems overly complex and there's a lot of custom statements that harm maintainability.

If it makes little sense to abstract something to a component since there's probably no relation it might make sense to add it to the theme or global CSS if appropriate. Or use abstractions and components already in place.

---
I've looked at the gist of the modal code so far, mainly architecturally. I've not thoroughly checked the snaps since this PR has gotten very large for 1 review, especially since another ticket was apparently merged into it.

2020-10-05 15:01 UTC, robinsiep commented on src/components/NavBar.jsx
>  import React from 'react';
There's a lot of void space between the logo and the links, probably a bit much since it'll never get filled.

On mobile I'd strongly recommend against putting the `Add new agent` button behind an overflow menu. It's (at least currently) your primary action on the dashboard and the user will have to search for it now.

If it doesn't fit nicely in the navbar I'd just move it to its context area which is the agent list. That's where the user will start looking first. It'll scale better when the dashboard grows and it makes discovery on desktop slightly better too.

2020-10-05 15:01 UTC, robinsiep commented on .env
> +APOLLO_BASE_HTTP_URL=http://localhost:
I'd consider renaming this to `EXTERNAL_APOLLO_HTTP_URL` and just include the port probably (since the other fields named `..URL` include the port.

We need to make it clear this URL is the one you need to be able to ping from the compromised machine so that's why I'd inlcude `EXTERNAL` or something even clearer.

2020-10-05 15:01 UTC, robinsiep commented on src/components/CopyToClipboard.jsx
> +  cursor: pointer;
What's the reasoning behind the choice of `pointer`? Wouldn't the `text` cursor be more fitting since it doesn't support on-click but rather supports selection in order to be copied?

2020-10-05 15:01 UTC, robinsiep commented on src/components/Dropdown.jsx
> +  closeDropdown = (e) => {
Still a decent amount of this notation which is fine if we consistently refactor and stick to it.

2020-10-05 15:01 UTC, robinsiep commented on src/components/Input.jsx
> +  color: ${props => props.inverted ? props.theme.white : "" };
`""` isn't a valid value for the `color` property I think. Maybe `inherit` or something from our `props.theme` makes sense as a default.

2020-10-05 15:01 UTC, robinsiep commented on src/components/NavBar.jsx
> +      bottom: ${props => props.collapsed ? 'static' : '0px'};
`static` isn't a correct value for `bottom`.

2020-10-05 15:01 UTC, robinsiep commented on src/components/NavBar.jsx
> +      maring-bottom: 32px;
```suggestion
      margin-bottom: 32px;
```

But if unnoticed then probably redundant.

2020-10-05 15:01 UTC, robinsiep commented on src/components/NavBar.jsx
> +const MenuToggleIcon = styled.i`
Don't you want this to extend `Icon`?

2020-10-05 15:01 UTC, robinsiep commented on src/store.js
> +export const store = createStore(persistedReducer, window.__REDUX_DEVTOOLS_EXTENSION__ && window.__REDUX_DEVTOOLS_EXTENSION__());
It might make sense to add `redux-devtools-extension`. Currently we'd be adding undefined dependencies to our store.

2020-10-05 15:01 UTC, robinsiep commented on tests/App.test.jsx
> +      notifications: new Map({}),
this is duplicated and would be alphabetically wrong

2020-10-05 15:01 UTC, robinsiep commented on tests/components/Login.test.jsx
> +      selectedArchitecture: "amd64",
This shouldn't be necessary I hope? Redux shouldn't be involved internal state to add an agent ( I haven't checked the modal implementation yet at the time of writing).

2020-10-05 15:01 UTC, robinsiep commented on tests/components/NavBar.test.jsx
> +  it('handles add agent modal', async () => {
Why is this `async`? I don't any async logic in the test.

2020-10-05 15:01 UTC, robinsiep commented on tests/pages/Dashboard.test.jsx
> +      authenticated: true,
duplicated.

2020-10-05 15:01 UTC, robinsiep commented on src/components/modals/add-agent/AddAgentModal.jsx
> +          agentId={this.state.agentId} />
I'd treat this data as an object rather than individually (with the exception of `manualUpload` and `onClose`).

2020-10-05 15:01 UTC, robinsiep commented on src/components/modals/add-agent/AddAgentModal.jsx
> +     content = this.renderQuestion();
Indentation.

2020-10-05 15:01 UTC, robinsiep commented on src/components/modals/add-agent/AddAgentModal.jsx
> +	};
Indentation, unsure of more occurrences throughout the PR so please make sure.

2020-10-05 15:01 UTC, robinsiep commented on src/components/modals/add-agent/AddAgentModal.jsx
> +
```suggestion
```

2020-10-05 15:01 UTC, robinsiep commented on src/components/modals/add-agent/AddAgentModal.jsx
> +const ColumnOne = styled.div`
Some duplication / coupling with the other column. also the margin statements can probably be replaced with grid statements.

2020-10-05 15:01 UTC, robinsiep commented on src/components/modals/add-agent/AddAgentModal.jsx
> +  renderQuestion = () => {
This makes the component pretty hard to read. Ideally I think you'd expect this modal to be a state manager for 3 components (the 3 "pages") with very little logic of its own. You've kinda got this but then this part is a method rather than external component, cluttering your code and CSS for 1 of the 3 pages.

I understand the abstraction of the first page is not as obvious. On the other hand it's also a bit ambiguous why this page is included in the component while the other two aren't and as I said it does make it harder to read. maybe abstracting it to a `Choice` component or something would work?

2020-10-05 15:01 UTC, RobinSiep commented on tests/lib/NewAgentHandler.test.jsx
> +      'test', 'test', 'test', 'test'
How do you verify that the values end up on the right arguments this way?

2020-10-06 12:53 UTC, rikvanderwerf commented on src/components/Dropdown.jsx
> +  closeDropdown = (e) => {
Changed them to the current notation for now.

2020-10-07 08:08 UTC, RobinSiep commented
Working on the next review right now but I thought I'd already comment on a bug that appears at least on my machine (`develop` API branch). I get this console error when creating an agent and can't move to the next screen in the modal, the agent is successfully created however and there seems to be no API error:
![image](https://user-images.githubusercontent.com/5303534/95304545-158a7480-0885-11eb-98e7-cffeb7849163.png)

2020-10-07 08:59 UTC, RobinSiep requested changes
I've ignored some more minor issues for the sake of moving this along. We might encounter some reusability issues of components due to their CSS introducing some scaling issues among other things.

2020-10-07 08:59 UTC, robinsiep commented on package.json
> +    "jest": "^26.5.0",
Why was this removed from the dev dependencies and added here?

2020-10-07 08:59 UTC, robinsiep commented on package.json
> +    "styled": "^1.0.0",
What is this? I don’t thiiiiink I see it being used.

2020-10-07 08:59 UTC, robinsiep commented on src/App.jsx
> +    color: ${(props) => props.theme.white};
Why all these changes enforcing `()` around single arguments? It's an opinionated change that's out of scope and would have to make documented in a styleguide of some sorts. This PR doesn't benefit from more out of scope changes.

2020-10-07 08:59 UTC, robinsiep commented on src/App.jsx
> +              <ProtectedRoute exact path="/" component={Dashboard} fallbackComponent={Welcome} />
Why the quote changes? I'm fine with enforcing double quotes _everywhere_ through a styleguide but that's out of scope for this PR. Until then I'd recommend sticking with the single quote of uninterrupted strings that we use in other projects.

The change to double quotes isn't consistently introduced in this PR either since there's still plenty of single quotes left so if you really want to introduce this into the scope of your PR as well you'd need to replace those as well.

2020-10-07 08:59 UTC, RobinSiep commented on src/components/modals/add-agent/AddAgent.jsx
> +const StyledCopyToClipboard = styled(CopyToClipboard)`
Does this work? I don't see the `className` property being passed in the `CopyToClipboard` component.

2020-10-07 08:59 UTC, RobinSiep commented on src/components/agent-list/AgentList.jsx
> -  min-width: 0;
Is this and the padding change intentional? I remember that you introduced the padding change last PR to improve consistency with `UserList`. Removing `min-width` is error-prone as a CSS grid item using `fr`.

2020-10-07 08:59 UTC, RobinSiep commented on src/components/agent-list/AgentList.jsx
> +      handleError('Something went wrong fetching the agent list');
I don't really understand this change. Based on our current implementations this should be a double quote. Earlier in this PR changes were made to seemingly change _everything_ into double quote which would mean this should be a double quote regardless right?

2020-10-07 08:59 UTC, RobinSiep commented on tests/App.test.jsx
> -      agent: [],
Why the change? I don't care too much if these are ordered alphabetically for readability but I don't really see a reason to change it either.

2020-10-07 08:59 UTC, RobinSiep commented on tests/components/Login.test.jsx
> +      authenticated: false,
in `App.jsx` I saw a change to remove trailing `,` whereas here one was added. When I read `App.jsx` I figured it was the work of a linter running over the project but now I'm not so sure.

2020-10-07 08:59 UTC, RobinSiep commented on tests/components/NavBar.test.jsx
> +  it('toggles collapsed', () => {
A snapshot assertion would be useful here.

2020-10-07 08:59 UTC, RobinSiep commented on tests/components/__snapshots__/Card.test.jsx.snap
> -  box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -2px rgba(0,0,0,0.05);
As I've said in the previous review, this PR grew too large for me to thoroughly review snapshots so I hope this was done. This change one line change popped out as kind of odd though. The `box-shadow` property comes from the `theme` now but according to this snapshot something goes wrong?

2020-10-07 14:47 UTC, rikvanderwerf commented on tests/components/__snapshots__/Card.test.jsx.snap
> -  box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -2px rgba(0,0,0,0.05);
Properties from theme only get loaded when we provide a theme with the `ThemeProvider` in the test. I can add it if you want. But we currently almost never do it.

2020-10-07 14:54 UTC, RobinSiep commented on tests/components/__snapshots__/Card.test.jsx.snap
> -  box-shadow: 0 10px 15px -3px rgba(0,0,0,0.1),0 4px 6px -2px rgba(0,0,0,0.05);
Ah yea I figured it had a `ThemeProvider` because the component accesses another theme property but I see now that that one also gets injected.

2020-10-08 06:55 UTC, rikvanderwerf commented
sorry for this thing being so damn long.

2020-10-08 08:10 UTC, RobinSiep approved these changes

2020-10-08 08:10 UTC, merged