Ap 49 user deletion
thecoderstudio/apollo-web pull request #14
Opened 2020-08-25 11:10 UTC by rikvanderwerf

Code R Ticket
Please provide a link to the Code R Jira ticket if applicable

https://partypeak.atlassian.net/browse/AP-49

Description
Adds the option to delete a non admin user.

![image](https://user-images.githubusercontent.com/5989836/91167536-6890d980-e6d4-11ea-926c-1842c3740a27.png)

Dependencies
Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests

Additional notes
Added the modal I build in the download binary branch.
Also no error handling. But i was thinking maybe we can add some sort of toast for this.

Also the confirmation text is now in the title of the modal. But that may be a bit large. let me know what u think

2020-08-28 08:54 UTC, RobinSiep requested changes
I think you'd expect to have a modal abstraction feature dismissal when clicking outside of the modal.

2020-08-28 08:54 UTC, RobinSiep commented on src/components/buttons/OutlinedButton.jsx
> +  &:active {
`Button` already contains this CSS because you've added it.

2020-08-28 08:54 UTC, RobinSiep commented on src/components/modals/ConfirmationModal.jsx
> +  confirmationButtonText: 'confirm'
```suggestion
  confirmationButtonText: 'Confirm'
```

2020-08-28 08:54 UTC, RobinSiep commented on src/components/modals/ConfirmationModal.jsx
> +  grid-template-columns: [cancel] 1fr [delete] 1fr;
This component is called a `ConfirmationModal` but here you're talking about `delete`.

2020-08-28 08:54 UTC, RobinSiep commented on src/components/modals/ConfirmationModal.jsx
> +            <CancelButton onClick={props.cancelCallback}>cancel</CancelButton>
```suggestion
            <CancelButton onClick={props.cancelCallback}>Cancel</CancelButton>
```

2020-08-28 08:54 UTC, RobinSiep commented on src/components/modals/ModalOverlay.jsx
> +
```suggestion
```

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserList.jsx
> +class UserList extends React.Component {
What's the reasoning behind switching away from `PureComponent` and moving the export statement?

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserListItem.jsx
> +  userDeleteCallback: PropTypes.func.isRequired
Why'd this be required? This pollutes the callsite if I wouldn't want to subscribe to the deletion.

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserListItem.jsx
> +import checkIfAdmin from '../../util/admin';
import ordering

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserListItem.jsx
> +const DeleteButton = styled(OutlinedButton)`
Why is this a button rather than an icon? Especially on mobile this is less than ideal.

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserListItem.jsx
> +  grid-column: logout;
This column doesn't exist I think, nor would it make any sense to exist.

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserListItem.jsx
> +  deleteUser() {
Don't make this the responsibility of the list item. You can create a component and using composition extend your current dialog and add functionality on top of it so that you have a component responsible for 1 single thing. If we add everything to the list item it's going to become messy and lose sight of its responsibility.

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserListItem.jsx
> +            confirmationButtonText='delete'
```suggestion
            confirmationButtonText='Delete'
```

2020-08-28 08:54 UTC, RobinSiep commented on src/components/user/UserListItem.jsx
> +          <DeleteButton onClick={this.showConfirmationModal}>delete</DeleteButton>
```suggestion
          <DeleteButton onClick={this.showConfirmationModal}>Delete</DeleteButton>
```

2020-08-28 08:54 UTC, RobinSiep commented on src/util/admin.jsx
> +
```suggestion
```

2020-08-28 08:54 UTC, RobinSiep commented on tests/components/modals/ConfirmationModal.test.jsx
> +    <Provider theme={darkTheme} store={configureStore([])({})}>
I don't think passing `theme` here would do anything? It's passed to the Redux provider.

2020-08-28 08:54 UTC, RobinSiep commented on tests/components/user/UserList.test.jsx
> +        <UserList />
```suggestion
      <UserList />
```

2020-08-28 08:54 UTC, RobinSiep commented on tests/components/user/UserList.test.jsx
> +    process.env = {
this is done in `setupTests.js`

2020-08-28 08:54 UTC, RobinSiep commented on tests/components/user/UserList.test.jsx
> +        id: 'id',
Front-end doesn't expect nor require the role id. Back-end doesn't return it.

2020-08-28 08:54 UTC, RobinSiep commented on tests/components/user/UserListItem.test.jsx
> +  const spy = jest.fn();
```suggestion
  const spy = jest.fn();

```

2020-08-28 08:54 UTC, RobinSiep commented on tests/components/user/UserListItem.test.jsx
> +    axios.delete.mockResolvedValue({
No need this mock this in this case.

2020-08-28 08:54 UTC, RobinSiep commented on tests/components/user/UserListItem.test.jsx
> +  it("correctly opens confirmation modal", async () => {
This test does more than just asserting whether the modal gets opened.

2020-08-28 08:54 UTC, RobinSiep commented on tests/pages/Admin.test.jsx
> +        id: 'id',
role doesn't have an id.

2020-08-28 08:54 UTC, RobinSiep commented on tests/pages/Admin.test.jsx
> +    process.env = {
done in `setupTests.js`

2020-08-28 08:54 UTC, RobinSiep commented on tests/util/admin.test.jsx
> +it('checks if admin correctly', () => {
```suggestion
test('checks if admin correctly', () => {
```

2020-08-28 09:02 UTC, rikvanderwerf commented on src/components/user/UserList.jsx
> +class UserList extends React.Component {
Needed it when i changed something but reverted it, but forgot this.

2020-08-28 10:26 UTC, rikvanderwerf commented on tests/components/modals/ConfirmationModal.test.jsx
> +    <Provider theme={darkTheme} store={configureStore([])({})}>
😂

2020-09-02 08:06 UTC, RobinSiep requested changes

2020-09-02 08:06 UTC, robinsiep commented on package-lock.json
> +{
Preferably use yarn. We should probably gitignore this one.

2020-09-02 08:06 UTC, robinsiep commented on src/actions/error.js
> +  const message = response.detail ? response.detail : response.statusText;
`response.detail` doesn't exist according to the documentation, has this been tested? You might mean `response.data.detail`.

https://github.com/axios/axios#response-schema

2020-09-02 08:06 UTC, robinsiep commented on src/components/user/DeleteUser.jsx
> +        confirmationBu ttonColor={this.props.theme.error}
```suggestion
        confirmationButtonColor={this.props.theme.error}
```

2020-09-02 08:06 UTC, robinsiep commented on src/components/user/UserListItem.jsx
> +)(withTheme(UserListItem));
I don't thiiink I see the `theme` property being used in the component?

2020-09-02 08:06 UTC, robinsiep commented on tests/actions/error.test.js
> +    const response = { status: 400, detail: "error", statusText: "bad request" };
Unrealistic response, doesn't match documented schema.

2020-09-02 08:06 UTC, robinsiep commented on tests/actions/error.test.js
> +  it("notifies of unsuccessful response wit herror detail", () => {
```suggestion
  it("notifies of unsuccessful response with error detail", () => {
```

2020-09-02 08:06 UTC, robinsiep commented on tests/components/modals/ModalOverlay.test.jsx
> +import { mount } from 'enzyme';
What's the reason for `enzyme` over `react-test-renderer`?

2020-09-02 08:06 UTC, robinsiep commented on tests/components/user/DeleteUser.test.jsx
> +
Too many newlines.

2020-09-02 08:06 UTC, robinsiep commented on tests/components/user/DeleteUser.test.jsx
> +describe("Delete user", () => {
Wouldn't you in both cases want to assert whether your `closeFunction` has been called?

2020-09-02 08:06 UTC, robinsiep commented on tests/components/user/DeleteUser.test.jsx
> +      expect(spy).toHaveBeenCalledTimes(0);
```suggestion
      expect(spy).not.toHaveBeenCalled();
```

2020-09-02 08:06 UTC, robinsiep commented on tests/components/modals/ModalOverlay.test.jsx
> +    expect(spy).toHaveBeenCalledTimes(0);
```suggestion
    expect(spy).not.toHaveBeenCalled();
```

2020-09-02 08:06 UTC, RobinSiep commented on tests/components/user/UserListItem.test.jsx
> +    axios.delete.mockResolvedValue({
Is this necessary?

2020-09-02 08:06 UTC, RobinSiep commented on tests/components/user/UserListItem.test.jsx
> +    axios.delete.mockResolvedValue({
Presuming `tree.root.findAllByType('button')[0]` is the cancel button there should be no reason to mock right?

2020-09-02 12:46 UTC, rikvanderwerf commented on tests/components/modals/ModalOverlay.test.jsx
> +import { mount } from 'enzyme';
I needed to simulate a click both on the component and somewhere other then on the component. But the `onClick`  method needed to be called in both cases with a correct `e.target` value.

2020-09-03 10:57 UTC, RobinSiep requested changes

2020-09-03 10:57 UTC, RobinSiep commented on src/components/modals/ModalOverlay.jsx
> +      <Overlay ref={node => this.node = node} onClick={this.closeModal}>
We're using React >16.3, you can use `React.createRef()`.

2020-09-03 11:37 UTC, RobinSiep approved these changes

2020-09-03 11:37 UTC, merged