AP-55 - Change initial password
thecoderstudio/apollo-web pull request #19
Opened 2020-09-09 08:59 UTC by rikvanderwerf

## Code R Ticket
_Please provide a link to the Code R Jira ticket if applicable_

<https://partypeak.atlassian.net/browse/AP-55>

## Description
Prompts the admin to change his password if he logs in for for the first time. He can choose to skip this (this gets saved locally). 

## Dependencies
_Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests_

* Depends on xxx

## Additional notes
_Anything else you want to mention._

2020-09-17 13:47 UTC, RobinSiep requested changes
The flow can currently get the user stuck to the point they need to clear cache. If you login and then for whatever reason forget your old password or you reset the server for whatever reason you're stuck since you can't log out.

---

I'm also not sure about the 2 different input colors in what visually looks to the user to be the same form. Aside from the slight readability loss it suggests some kind of significance while in reality it's just arbitrary.

Additionally the readability loss on mobile is significant because we hide the card.
![image](https://user-images.githubusercontent.com/5303534/93479800-0905a280-f8fd-11ea-9306-1e039de01fc3.png)

2020-09-17 13:47 UTC, robinsiep commented on package.json
> +    "babel-jest": "26.3",
Preferably don't pin minor versions, you can increase the minimum though.

2020-09-17 13:47 UTC, robinsiep commented on src/components/Input.jsx
> +      <StyledInput hasError={error.length > 0} {...rest} />
This comparison is done the line right below. If you want to reuse it it should be lifted out and put in a variable.

2020-09-17 13:47 UTC, robinsiep commented on src/components/Input.jsx
> +  color: ${props => props.inverted ? props.theme.white : "" };
`""` isn't a valid color property value.

2020-09-17 13:47 UTC, robinsiep commented on src/components/ProtectedRoute.jsx
> +            authenticated && correctRole && this.props.currentUser.has_changed_initial_password ? <Component {...props} /> : <FallbackComponent {...props} />
A bit long, I'd lift out the comparison.

2020-09-17 13:47 UTC, RobinSiep commented on src/pages/Dashboard.jsx
> +const PasswordChange = styled(ChangePassword)`
Seemingly unused (which is good, I'm not entirely sure what it's doing here).

2020-09-17 13:47 UTC, RobinSiep commented on src/pages/Dashboard.jsx
> +    this.state = { initialPasscodeChanged : this.props.currentUser.has_changed_initial_password };
State set but seeming unused.

2020-09-17 13:47 UTC, RobinSiep commented on src/pages/Dashboard.jsx
> +    fetchCurrentUser(this.props.dispatch);
This already happens on login. Let's not do this every time the user navigates to the dashboard. We can introduce a global periodic refresh but the chance that the user sets their password through another client is pretty slim so I wouldn't do it in this ticket.

2020-09-17 13:47 UTC, RobinSiep commented on src/pages/Dashboard.jsx
>  import React from 'react';
When looking at the points mentioned below I don't think this file should've been altered at all.

2020-09-17 13:47 UTC, robinsiep commented on src/pages/Login.jsx
> -
Lets keep these newlines for readability sake. That goes for all of the deleted ones.

2020-09-17 13:47 UTC, RobinSiep commented on src/pages/Login.jsx
>  import Card from '../components/Card';
I wouldn't really expect many changes to this file. it's sole responsibility should be login but now it's also partially responsible for initialisation. If you want both features to have the same layout with the astronaut and everything that should just be lifted out.

From the perspective of this file `ChangePassword` seems almost correctly lifted but it doesn't belong in this file. This should all be fixable using composition.

2020-09-17 13:47 UTC, RobinSiep commented on src/util/user.js
> +export function fetchCurrentUser(dispatch, callback) {
Dispatch shouldn't be passed around. You can get a global dispatch from the `store` if you _need_ to.

2020-09-17 13:47 UTC, RobinSiep commented on src/validation/user.js
> +    .min(8, "Min 8 characters")
I'd rely on the server to validate the old password. This way we can easier migrate. I don't think it's up to a changePassword schema (form) to validate whether the old password to our guidelines but only that is exists. If it's less than 8 characters but it's the correct password then it's the correct password.

2020-09-17 13:47 UTC, robinsiep commented on src/validation/user.js
> +    .min(8, "Min 8 characters")
Duplicated strings should be put in a constant. See the `loginSchema`.

2020-09-17 13:47 UTC, robinsiep commented on tests/pages/Dashboard.test.jsx
>  import { Provider } from 'react-redux';
I'm skipping this file for now because of the presumed changes to its counterpart.

2020-09-17 13:47 UTC, robinsiep commented on tests/pages/Login.test.jsx
> -  it("handler get current user failure", async () => {
Whether `loginSuccessCallback` doesn't get called on failure now goes unasserted I think.

2020-09-17 13:47 UTC, robinsiep commented on tests/util/user.test.js
> +  it('handles unsuccessful call', async () => {
Don't you want to assert whether callback doesn't get called?

2020-09-17 13:47 UTC, robinsiep commented on src/validation/user.js
> +  password: Yup.string()
Ideally we'd validate that `oldPassword !== password` front-end too.

2020-09-17 13:47 UTC, robinsiep commented on src/components/user/ChangePassword.jsx
> +    if ((values['password'] === '' && values['passwordConfirm'] === '') || Object.keys(errors).length !== 0) {
Isn't `Object.keys(errors).length !== 0' all you have to do? At least currently with the aggressive validation.

2020-09-17 13:47 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> +  getButton(errors, values) {
No need to conditionally render the entire button and duplicating the string. All you need to do is give the property as true or false.

2020-09-17 13:47 UTC, robinsiep commented on src/components/user/ChangePassword.jsx
> +              value={values.oldPssword}
```suggestion
              value={values.oldPassword}
```
I'm not even really sure how this ever worked then 😁 I guess it's only passed initially.

2020-09-17 13:49 UTC, RobinSiep commented on src/App.jsx
> +    hasChangedPassword: state.currentUser.has_changed_initial_password,
`has_changed_initial_password` snake case suggests `currentUser` needs to be run through the parser. It wasn't yet because it returned no snake case values (arguably it should've been run through regardless).

2020-09-18 11:19 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> +    if ((values['password'] === '' && values['passwordConfirm'] === '') || Object.keys(errors).length !== 0) {
I've made a PR to change the validation to something less aggressive. If we opt for that I think the reverse would be true and you wouldn't have to do an error check.

2020-09-24 10:10 UTC, RobinSiep requested changes
> The flow can currently get the user stuck to the point they need to clear cache. If you login and then for whatever reason forget your old password or you reset the server for whatever reason you're stuck since you can't log out.

This issue still seems to exist.

2020-09-24 10:10 UTC, robinsiep commented on package.json
> +    "babel-jest": ">=26.3",
```suggestion
    "babel-jest": "^26.3",
```

2020-09-24 10:10 UTC, robinsiep commented on package.json
> +    "jest": ">=26.3",
```suggestion
    "jest": "^26.3",
```

2020-09-24 10:10 UTC, robinsiep commented on src/components/ProtectedRoute.jsx
> +    const AuthenticatedAndInitialised = authenticated && correctRole && this.props.currentUser.hasChangedInitialPassword;
```suggestion
    const authenticatedAndInitialised = authenticated && correctRole && this.props.currentUser.hasChangedInitialPassword;
```

2020-09-24 10:10 UTC, robinsiep commented on src/components/ProtectedRoute.jsx
> +          AuthenticatedAndInitialised ? <Component {...props} /> : <FallbackComponent {...props} />
```suggestion
          authenticatedAndInitialised ? <Component {...props} /> : <FallbackComponent {...props} />
```

2020-09-24 10:10 UTC, robinsiep commented on src/components/authentication/Login.jsx
> +export { Login };
```suggestion
export { Login as UnconnectedLogin };
```

Or something similar. If you don't you risk importing the other export instead.

2020-09-24 10:10 UTC, robinsiep commented on src/components/authentication/Login.jsx
> +  login = (credentials, { setErrors }) => {
I'd recommend against making the stylistic change to arrow function if we use plain function in the rest of the project. I'd strongly recommend against mixing the two function types in the same class.

2020-09-24 10:10 UTC, robinsiep commented on src/components/authentication/Login.jsx
> +  loginSuccessCallback = () => {
In addition to the above it's also just extra syntactic sugar in the case of class methods which just comes down to the same characters with extra clutter but that's subjective.

```
loginSuccessCallback = () => {
```

vs

```
loginSuccessCallback() {
```

2020-09-24 10:10 UTC, robinsiep commented on src/components/user/ChangePassword.jsx
> +  changePassword = (values, { setErrors }) => {
See comments in `Login.jsx`.

2020-09-24 10:10 UTC, robinsiep commented on src/components/user/ChangePassword.jsx
> +  getButtonState = (values) => {
This method name is unclear because you need to look where it's used to understand it. In other word, its readability is based on the callee. If you just look at this method alone then calling `getButtonState` will give you either `true` or `false`. What does it mean for the button state to be `true` or `false`?

2020-09-24 10:10 UTC, robinsiep commented on src/components/user/ChangePassword.jsx
> +    if (values['password'] === '' || values['passwordConfirm'] === '' ||
You should be able to simply do
```
return Object.values(values).some((value) => value === '')
```

2020-09-24 10:10 UTC, robinsiep commented on tests/components/user/ChangePassword.test.jsx
> +    process.env = {
This shouldn't be required. It's done in `setupTests.js`.

2020-09-24 10:10 UTC, robinsiep commented on tests/components/user/ChangePassword.test.jsx
> +
```suggestion
```

2020-09-24 10:10 UTC, RobinSiep commented on tests/components/Login.test.jsx
> -  it("handler get current user failure", async () => {
> Whether loginSuccessCallback doesn't get called on failure now goes unasserted I think.

I think this is still the case?

2020-09-24 10:10 UTC, RobinSiep commented on tests/pages/Welcome.test.jsx
> +      authenticated: false,
```suggestion
      authenticated: true,
```

The snapshot currently doesn't render change password. Make sure to verify the generated snapshots when creating snapshot tests.

2020-09-25 11:56 UTC, rikvanderwerf commented on src/components/authentication/Login.jsx
> +  login = (credentials, { setErrors }) => {
When doing it like this you don't have to bind the methods

2020-09-25 12:05 UTC, RobinSiep commented on src/components/authentication/Login.jsx
> +  login = (credentials, { setErrors }) => {
Well yea that's because they don't have their own bindings to `this` and `super`. We can refactor to this but we'd need to consistently introduce it everywhere rather than having it be some arbitrary choice. Currently we've been using explicit bindings.

2020-09-25 12:09 UTC, RobinSiep commented on src/components/authentication/Login.jsx
> +  login = (credentials, { setErrors }) => {
Also do keep in mind there's performance and (minor) testability cost, there's always a trade-off.

2020-09-25 13:23 UTC, rikvanderwerf commented on src/components/authentication/Login.jsx
> +  login = (credentials, { setErrors }) => {
Alright cool cool cool toit

2020-09-30 14:46 UTC, RobinSiep requested changes

2020-09-30 14:46 UTC, RobinSiep commented on tests/components/user/ChangePassword.test.jsx
> +    expect(tree).toMatchSnapshot();
Is this to just assert whether there’s no errors or something?

2020-09-30 14:46 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> +			.then(_ => {
tab indentation

2020-09-30 14:46 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> +	}
here too, there may be more.

2020-09-30 14:46 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> +    dispatch(removeCurrentUser());
Duplication with `NavBar.jsx` that makes it easy to change one but not the other and have 2 different logout implementations. This needs to be lifted out.

2020-09-30 14:46 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> +  getDisabledButtonState(values){
Still named after the callee rather than its functionality but I think it's clear enough. At least the return value makes some more sense now.

2020-09-30 14:46 UTC, RobinSiep commented on src/pages/Welcome.jsx
> +            {!this.props.authenticated ? <div>Log in to Apollo</div> : <div>Change your password</div>}
What's the reason for the divs? They seem unnecessary to me.

2020-09-30 14:46 UTC, RobinSiep commented on tests/components/Login.test.jsx
> -  it("handler get current user failure", async () => {
I think this is still the case? The removed code asserted whether or not the callback gets called when login succeeds but user fetch fails. `handles unsuccessful login` in turn asserted whether the user doesn't get fetched at all (by requiring 0 dispatches rather than 1).

I don't think any of these 2 conditions get asserted now.

2020-09-30 14:46 UTC, RobinSiep commented on tests/components/user/ChangePassword.test.jsx
> +  it('patch successfully', async () => {
This seems duplicate with the above. It at least has the same name but I think they're identical.

2020-10-02 10:22 UTC, RobinSiep requested changes

2020-10-02 10:22 UTC, robinsiep commented on src/components/NavBar.jsx
> +  return(
```suggestion
  return (
```

2020-10-02 10:22 UTC, robinsiep commented on src/components/user/ChangePassword.jsx
> +      if (error.response.status === StatusCodes.BAD_REQUEST) {
Indentation

2020-10-05 08:08 UTC, RobinSiep requested changes

2020-10-05 08:08 UTC, RobinSiep commented on src/App.jsx
> +import Login from './pages/Welcome';
```suggestion
import Welcome from './pages/Welcome';
```
I think?

2020-10-05 08:08 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> -    axios.patch(
Wrong indentation in most of this file.

2020-10-05 08:42 UTC, rikvanderwerf commented on src/components/user/ChangePassword.jsx
> -    axios.patch(
Hmm really?

2020-10-05 08:44 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> -    axios.patch(
![image](https://user-images.githubusercontent.com/5303534/95058394-c3681880-06f7-11eb-8965-b29b02195451.png)

2020-10-05 08:45 UTC, RobinSiep commented on src/components/user/ChangePassword.jsx
> -    axios.patch(
method body is aligned with method declaration.

2020-10-05 09:29 UTC, RobinSiep approved these changes

2020-10-05 09:29 UTC, merged