AP-64 agent detail page
thecoderstudio/apollo-web pull request #22
Opened 2020-09-25 08:49 UTC by RobinSiep

## Code R Ticket
_Please provide a link to the Code R Jira ticket if applicable_

<https://partypeak.atlassian.net/browse/AP-64>

## Description
Agent detail page with machine info, inline terminal and room for predefined actions to be executed on the agent.

## Dependencies
_Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests_

* https://github.com/thecoderstudio/apollo/pull/36

## Additional notes
Nope

2020-09-28 12:49 UTC, RobinSiep commented
Trying to trigger Codacy :D

2020-10-01 08:21 UTC, rikvanderwerf requested changes

2020-10-01 08:21 UTC, rikvanderwerf commented on src/components/connection-state/ConnectionIndicator.jsx
> +
```suggestion
```

2020-10-01 08:21 UTC, rikvanderwerf commented on tests/pages/AgentDetail.test.jsx
> +  it("renders unkown platform info correctly", () => {
```suggestion
  it("renders unknown platform info correctly", () => {
```

2020-10-02 10:02 UTC, rikvanderwerf approved these changes

2020-10-02 10:02 UTC, merged