AP-68 settings panel
thecoderstudio/apollo-web pull request #24
Opened 2020-10-07 11:20 UTC by rikvanderwerf

## Code R Ticket
_Please provide a link to the Code R Jira ticket if applicable_

<https://partypeak.atlassian.net/browse/AP-68>

## Description

Added a wheel to go to settings. Settingspages have a side navigation for navigation through the different settings.

![image](https://user-images.githubusercontent.com/5989836/95324333-de758c80-089f-11eb-9ff2-5111e7b47985.png)

![image](https://user-images.githubusercontent.com/5989836/95324346-e46b6d80-089f-11eb-810c-29cff6a1fc31.png)

![image](https://user-images.githubusercontent.com/5989836/95324376-ec2b1200-089f-11eb-87fc-c324e8eb11fd.png)

## Dependencies
_Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests_

*

## Additional notes
_Anything else you want to mention._

2020-10-08 09:33 UTC, RobinSiep requested changes
Settings link 404s on mobile

2020-10-12 10:25 UTC, RobinSiep requested changes

2020-10-12 10:25 UTC, RobinSiep commented on src/components/SettingsSideNavigation.jsx
> +        <StyledLink
I'd lift this out to something like a location aware link or something. Which this menu could then just take as children so that you could do (name is placeholder):
```
<SideNavigation>
	<LocationAwareLink to="/settings/user_settings">User settings</LocationAwareLink>
	...
</SideNavigation>
```

2020-10-12 10:25 UTC, RobinSiep commented on src/hoc/SettingsPage.jsx
> +function withSettingsNavigation(Component) {
Adding this as a HOC means that you'll add the navigation menu each time and rerender it each time I think too. Instead you'd probably want a settings page component with the navigation menu and a `Switch` from `react-router-dom` (I think that component should suffice).

2020-10-12 10:25 UTC, RobinSiep commented on tests/hoc/SettingsPage.test.jsx
> +import SettingsPage from '../../src/hoc/SettingsPage';
This test confuses me a little. Isn't this a HOC? Don't you want to test its HOC functionality? It's also imported under a different name.

2020-10-12 10:25 UTC, RobinSiep commented on src/hoc/SettingsPage.jsx
> +import React from 'react';
`SettingsPage.jsx` is this name correct?

2020-10-12 10:25 UTC, RobinSiep commented on tests/hoc/__snapshots__/SettingsPage.test.jsx.snap
> +exports[`settings page render correctly 1`] = `null`;
This snapshot seems to confirm the HOC test doesn't work as expected.

2020-10-13 08:05 UTC, RobinSiep requested changes
I've made a quick attempt to test this with an additional setting sub-page but didn't even manage to add an additional link but that could've been my uvicorn not reloading or something.

I've skipped an in-depth review for now in favour of reviewing the components composition and architecture.

2020-10-13 08:05 UTC, robinsiep commented on src/components/SettingsPageWrapper.jsx
> +export default function SettingsPageWrapper(props) {
This should be `SettingsPage` and should be on the component rendered by the `/settings/...` route. You should be able to match on inexact path to accomplish this.

2020-10-13 08:05 UTC, robinsiep commented on src/components/SettingsPageWrapper.jsx
> +      <Switch>
Has this been tested with multiple setting pages? I don't really see how this would work currently. `Switch` should only have `Route` or `Redirect` as its children. It should be responsible for conditionally rendering your setting page content, not your navigation (using exact routes).

Right now I think the Switch does nothing or breaks stuff.

2020-10-13 08:05 UTC, robinsiep commented on src/components/SettingsSideNavigation.jsx
> +      <PathAwareLink location={location} to='/settings/user_settings'>User settings</PathAwareLink>
I'd rename this component to `SideNavigation` and allow these `PathAwareLinks` to be given as children. The component should have nothing specifically to do with settings.

2020-10-13 08:05 UTC, robinsiep commented on src/components/links/PathAwareLink.jsx
> +        <StyledIcon className="fas fa-user-cog" />
I think this should be configurable to allow for reusability.

2020-10-13 08:05 UTC, RobinSiep commented on src/pages/settings/UserSettings.jsx
> +    <SettingsPageWrapper {...props}><div /></SettingsPageWrapper>
Using that component as a wrapper most likely still causes the rerender and is less preferable than just rendering settings page content conditionally.

2020-10-15 07:43 UTC, RobinSiep requested changes

2020-10-15 07:43 UTC, RobinSiep commented on src/components/action/Action.jsx
> -  const { title, children, agentId, endpoint, disabled, ...rest } = props;
nah

2020-10-15 07:43 UTC, RobinSiep commented on src/components/links/PathAwareLink.jsx
> +  ${media.phone`
```suggestion
  ${
    media.phone`
```

2020-10-15 07:43 UTC, RobinSiep commented on src/components/links/PathAwareLink.jsx
> +    margin: 0 auto;
```suggestion
      margin: 0 auto;
```

2020-10-15 07:43 UTC, RobinSiep commented on src/components/links/PathAwareLink.jsx
> +  `}
```suggestion
    `
  }
```

2020-10-15 07:43 UTC, RobinSiep commented on src/components/links/PathAwareLink.jsx
> +  ${media.phone`
same as above.

2020-10-15 07:43 UTC, RobinSiep commented on tests/components/SideNavigation.test.jsx
> +      <SideNavigation {...props} />
I'd render this with one or multiple child component(s) to match its realistic use-case. Especially since `children` is a required property on this component.

2020-10-15 07:43 UTC, RobinSiep commented on src/pages/settings/SettingsPage.jsx
> +          <Route exact path={`${match.url}/user_settings`} component={UserSettings} />
You may want to consider adding the `NotFound` page as your default route when this route doesn't match. Currently unknown setting paths go unhandled but `NotFound` should nest properly as content of this page too.

2020-10-16 08:05 UTC, RobinSiep requested changes

2020-10-16 08:05 UTC, robinsiep commented on src/components/links/PathAwareLink.jsx
> +	to: PropTypes.string.isRequired,
tabs

2020-10-16 08:05 UTC, robinsiep commented on src/components/links/PathAwareLink.jsx
> +  `}
^

2020-10-16 08:05 UTC, robinsiep commented on src/components/links/PathAwareLink.jsx
> +	constructor(props) {
tabs

2020-10-16 08:05 UTC, robinsiep commented on src/components/links/PathAwareLink.jsx
> +	checkIfPathIsActive(path) {
tabs

2020-10-16 08:05 UTC, robinsiep commented on src/components/links/PathAwareLink.jsx
> +	render() {
tabs

2020-10-16 08:05 UTC, RobinSiep commented on tests/pages/settings/SettingsPage.test.jsx
>  describe("settings page", () => {
I'd also add a snapshot test that asserts whether the user settings get rendered given the correct path. This test now (correctly) generates a snapshot with 404 content.

2020-10-16 11:49 UTC, RobinSiep requested changes

2020-10-16 11:49 UTC, RobinSiep commented on tests/pages/settings/SettingsPage.test.jsx
> +import { BrowserRouter, MemoryRouter } from 'react-router-dom';
`BrowserRouter` unused I think.

2020-10-26 11:27 UTC, RobinSiep approved these changes

2020-10-26 11:28 UTC, merged