AP-20 login
thecoderstudio/apollo-web pull request #4
Opened 2020-06-16 10:41 UTC by RobinSiep

## Code R Ticket
_Please provide a link to the Code R Jira ticket if applicable_

<https://partypeak.atlassian.net/browse/AP-20>

## Description
Adds a response login screen and full test coverage.

![image](https://user-images.githubusercontent.com/5303534/84764666-61f82e80-afce-11ea-8018-e05ffe73076a.png)
![image](https://user-images.githubusercontent.com/5303534/84764767-8522de00-afce-11ea-8c46-b856c5eeac95.png)
![image](https://user-images.githubusercontent.com/5303534/84764707-72100e00-afce-11ea-99eb-388e3b6f9456.png)

## Dependencies
_Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests_

*

## Additional notes
Doesn't include error handling yet because I think this is best dealt with as a more global solution that's out of scope.

2020-06-16 10:41 UTC, RobinSiep commented
# [Codecov](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4?src=pr&el=h1) Report
> :exclamation: No coverage uploaded for pull request base (`develop@ec1e0e8`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> The diff coverage is `100.00%`.

[![Impacted file tree graph](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/graphs/tree.svg?width=650&height=150&src=pr&token=wdJRwBwZJ4)](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4?src=pr&el=tree)

```diff
@@             Coverage Diff             @@
##             develop        #4   +/-   ##
===========================================
  Coverage           ?   100.00%           
===========================================
  Files              ?        13           
  Lines              ?        83           
  Branches           ?        14           
===========================================
  Hits               ?        83           
  Misses             ?         0           
  Partials           ?         0           
```


| [Impacted Files](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [src/App.jsx](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL0FwcC5qc3g=) | `100.00% <100.00%> (ø)` | |
| [src/actions/auth.js](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL2FjdGlvbnMvYXV0aC5qcw==) | `100.00% <100.00%> (ø)` | |
| [src/actions/theme.js](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL2FjdGlvbnMvdGhlbWUuanM=) | `100.00% <100.00%> (ø)` | |
| [src/components/Button.jsx](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL2NvbXBvbmVudHMvQnV0dG9uLmpzeA==) | `100.00% <100.00%> (ø)` | |
| [src/components/Card.jsx](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL2NvbXBvbmVudHMvQ2FyZC5qc3g=) | `100.00% <100.00%> (ø)` | |
| [src/components/Input.jsx](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL2NvbXBvbmVudHMvSW5wdXQuanN4) | `100.00% <100.00%> (ø)` | |
| [src/components/ProtectedRoute.jsx](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL2NvbXBvbmVudHMvUHJvdGVjdGVkUm91dGUuanN4) | `100.00% <100.00%> (ø)` | |
| [src/pages/Dashboard.jsx](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL3BhZ2VzL0Rhc2hib2FyZC5qc3g=) | `100.00% <100.00%> (ø)` | |
| [src/pages/Login.jsx](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL3BhZ2VzL0xvZ2luLmpzeA==) | `100.00% <100.00%> (ø)` | |
| [src/reducers/auth.js](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree#diff-c3JjL3JlZHVjZXJzL2F1dGguanM=) | `100.00% <100.00%> (ø)` | |
| ... and [16 more](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4?src=pr&el=footer). Last update [ec1e0e8...96e682a](https://codecov.io/gh/thecoderstudio/apollo-web/pull/4?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

2020-06-16 15:40 UTC, rikvanderwerf requested changes

2020-06-16 15:40 UTC, rikvanderwerf commented on tests/components/ProtectedRoute.test.jsx
> +
```suggestion
```

2020-06-18 12:15 UTC, rikvanderwerf approved these changes

2020-06-18 12:15 UTC, merged