Ap 31 agent listing
thecoderstudio/apollo-web pull request #5
Opened 2020-06-30 08:08 UTC by rikvanderwerf

## Code R Ticket
_Please provide a link to the Code R Jira ticket if applicable_

<https://partypeak.atlassian.net/browse/AP-31>

## Description
Implements basic agent listing in the dashboard. 

- Doesn't give the user feedback on an error (other then 403). Thought maybe we want a more generic way of error handling which seemed out of scope. 

## Dependencies
_Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests_

*

## Additional notes

Tried everything in my power to fix these tests but failed. I do have 100% coverage. But tests I would have liked to make were:

- check if `logout` action was dispatched on 403.  
- check if 'listAgent' action was dispatched on succes. 

But whatever i tried, dispatched was never called according to the `expect` function. But I'm 100% sure it does get called so i have no clue. I'm sure we can fix it tho. Or maybe my whole view on testing these components is wrong.

2020-06-30 12:03 UTC, RobinSiep commented
> Also codacy "unnecessary block" seems weird to me.

The Codacy comments all seem justified. That block is unnecessary, see other reducers.

2020-08-21 08:30 UTC, RobinSiep requested changes
I'm not sure if I caught all CSS issues. What's important there is minimising coupling, conciseness and reusability.

2020-08-21 08:30 UTC, robinsiep commented on package.json
> +    "eslint": "^7.3.1",
If we want to install eslint it should also be setup and not be in the git ignore. The rc should reflect Codacy.

2020-08-21 08:30 UTC, robinsiep commented on src/components/Content.jsx
> +const ContentContainer = styled.div`
I don't see the point of this component. Especially declaring `grid-row` out of context like this is very specific to its parent component and can't really be done.

2020-08-21 08:30 UTC, robinsiep commented on src/components/Text.jsx
> +  grid-column: name;
Similarly to Content, we can't just define a ambiguous `grid-column` in a generic component like this. Other than that I also question it's usage over styling the default text tags and using them in a project wide manner like we're currently doing (`h1`-`h6`, `p`).

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentList.jsx
> +import React from 'react';
Import ordering as we've discussed in a previous PR (can't quite remember which one).

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentList.jsx
> +  grid-column: agent-listing;
We can't define a `grid-column` in a top level component like this. It lacks context and harms its reusability. That kind of styling should just be done in the parent file.

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentList.jsx
> +
```suggestion
```

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentList.jsx
> +      return <AgentListItem key={agent.id} agentName={agent.name} connectionState={agent.connection_state} />;
`connection_state` isn't camelcase but I've parsed the agent JSON in the terminal PR that builds on this so it doesn't require a fix right now.

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentListItem.jsx
> +import React from 'react';
See comment about import ordering above. I'm sure this is going on in more files but I'll not point it out in each.

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentListItem.jsx
> +  agentName: PropTypes.string.isRequired,
I'd just request the entire `agent` but I've done so in the terminal PR so no need to fix here.

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentListItem.jsx
> +AgentListItem.propTypes = propTypes;
I'm questioning whether this will now work on the exported component. I don't thiiink so?

2020-08-21 08:30 UTC, robinsiep commented on src/components/agent-list/AgentListItem.jsx
> +const StyledText = styled(Text)`
See comment on the `Text` component. It's probably better to use one of the available text tags to get project wide consistency. If they're lacking in range we can add to them but `Text` isn't very clear on what it's purpose would be in relation to the other text tags.

2020-08-21 08:30 UTC, RobinSiep commented on src/components/agent-list/ConnectionState.jsx
> +        <Indicator connectionState={props.connectionState} />
I'd pass the desired color rather than the state, that way you avoid doing the switch statement twice.

2020-08-21 08:30 UTC, RobinSiep commented on src/components/agent-list/ConnectionState.jsx
> +  float: right;
Positioning like this should generally be left to the component that _uses_ this component.

2020-08-21 08:30 UTC, RobinSiep commented on tests/actions/agent.test.js
> +    type: LIST_AGENTS
I'd also assert whether the agents you give it get passed back to you. See the `actions/theme.test.js` for example.

2020-08-21 08:30 UTC, RobinSiep commented on tests/components/agent-list/AgentList.test.jsx
> +    expect(component.root.findAllByType("li").length).toBe(2);
Isn't this replaceable by a snapshot test to be more concrete about what you expect?

2020-08-21 08:30 UTC, RobinSiep commented on tests/components/agent-list/__snapshots__/ConnectionState.test.jsx.snap
> +exports[`connectionState Gets correct color 3`] = `
Correct me if I'm wrong but I don't see a difference between the different color snapshots. This either means it's not working or we can't assert this way. I've added `jest-styled-components` in the Terminal PR which may help you out.

2020-08-21 08:30 UTC, RobinSiep commented on tests/reducers/agent.test.js
> +  it("should return empty agent list as initial state", () => {
It returns `[]` as an initial state as this is what's defined in your reducer. What you're doing now is passing it a state of `{ agents: [] }` and then asserting whether that's returned.

2020-08-21 08:30 UTC, RobinSiep commented on tests/reducers/agent.test.js
> +    })).toEqual([{ id: "id" }]);
```suggestion
    })).toEqual(agents);
```

2020-08-21 09:40 UTC, rikvanderwerf commented on src/components/agent-list/AgentListItem.jsx
> +AgentListItem.propTypes = propTypes;
it does work :)

2020-08-21 09:48 UTC, rikvanderwerf commented on src/components/agent-list/ConnectionState.jsx
> +        <Indicator connectionState={props.connectionState} />
hmm, I only have the props.theme in a styled component.

2020-08-21 09:50 UTC, robinsiep commented on src/components/agent-list/ConnectionState.jsx
> +        <Indicator connectionState={props.connectionState} />
Use [withTheme](https://styled-components.com/docs/advanced)

2020-08-21 09:51 UTC, rikvanderwerf commented on src/components/agent-list/ConnectionState.jsx
> +  float: right;
I dont understand. the parent components has his width defined by the grid-column. so for all the children to float right i have to do it like this right?

2020-08-21 09:52 UTC, rikvanderwerf commented on src/components/agent-list/ConnectionState.jsx
> +        <Indicator connectionState={props.connectionState} />
thanks

2020-08-21 09:56 UTC, robinsiep commented on src/components/agent-list/ConnectionState.jsx
> +  float: right;
This makes the `ContentWrapper` and thus the component float right which is a weird default out of context. I get that you want the component to float right in its parent in the context of the list item thus this styling should be done in that file using `styled(ConnectionState)`.

Just like an `<a>` tag doesn't float right by default. If you want it to float right you add this styling when using it.

2020-08-21 10:20 UTC, rikvanderwerf commented on src/components/agent-list/ConnectionState.jsx
> +  float: right;
Alright makes sense. But i will have to wrap the `ConnectionState` inside a `ConnectionStateWrapper` instead of `styled(ConnectionState)`. Because styling a react component doesn't do anything right? (at least when i try it :D)

2020-08-21 10:22 UTC, robinsiep commented on src/components/agent-list/ConnectionState.jsx
> +  float: right;
That's because you're not passing the `className` property. https://styled-components.com/docs/advanced

2020-08-21 10:25 UTC, rikvanderwerf commented on src/components/agent-list/ConnectionState.jsx
> +  float: right;
Maybe i should read the docs better 🌚 ?

2020-08-21 10:28 UTC, robinsiep commented on src/components/agent-list/ConnectionState.jsx
> +  float: right;
🤓

2020-08-24 10:35 UTC, RobinSiep commented
Codacy

2020-08-24 11:16 UTC, rikvanderwerf commented
Updated, and i believe we can ignore the other ones?

2020-08-24 14:36 UTC, RobinSiep requested changes
Do you get this too? I don't get it on dev.

![image](https://user-images.githubusercontent.com/5303534/91052834-50f91880-e622-11ea-9597-f25c370178c3.png)

(when having the dev tools installed)

2020-08-24 14:36 UTC, robinsiep commented on src/components/agent-list/AgentList.jsx
> +  maring: 20px;
typo, if not noticed the statement is probably obsolete?

2020-08-24 14:36 UTC, robinsiep commented on src/components/agent-list/AgentListItem.jsx
> +const StyledText = styled.span`
Ideally extend 1 of the text tags rather than span. This way it'll be easier for us to keep text consistent. Alternatively use composition.

2020-08-24 14:36 UTC, robinsiep commented on src/components/agent-list/ConnectionState.jsx
> +const StyledText = styled.span`
See comment concerning text in `AgentListItem`

2020-08-24 14:36 UTC, robinsiep commented on tests/components/agent-list/ConnectionState.test.jsx
> +    expect(tree).not.toHaveStyleRule('color', darkTheme.connectedColor);
I like this for verbosity because it's much easier to read than the snapshot so we should definitely keep it but I just wanted to comment that it wasn't strictly necessary now that we have the `jest-styled-components` package. The colors are mentioned in the snapshot (but again, much harder to read).

2020-08-25 11:55 UTC, rikvanderwerf commented on src/components/agent-list/AgentListItem.jsx
> +const StyledText = styled.span`
hmm but the `p` tags adds margins i don't want and the header tags are for headers which this is not. But the way i set it up before was invalid you said so I dont know what to do now :D

2020-08-25 11:57 UTC, rikvanderwerf commented on tests/components/agent-list/ConnectionState.test.jsx
> +    expect(tree).not.toHaveStyleRule('color', darkTheme.connectedColor);
ahh yeah i see now

2020-08-25 12:00 UTC, RobinSiep commented on src/components/agent-list/AgentListItem.jsx
> +const StyledText = styled.span`
You take the `p` tag and style it to your liking instead of basing off of a `span` tag.

2020-08-25 12:06 UTC, RobinSiep commented on src/components/agent-list/AgentListItem.jsx
> +const StyledText = styled.span`
And of course you can also add an extra component that doesn't serve the use case of neither the heading tags nor the paragraph tags but then it should be properly named after its usecase rather than something ambiguous like `Text`.

2020-08-25 12:21 UTC, rikvanderwerf commented
> Do you get this too? I don't get it on dev.

I have it too but wtf 😂

2020-08-25 12:42 UTC, RobinSiep requested changes

2020-08-25 12:42 UTC, RobinSiep commented on src/components/agent-list/AgentListItem.jsx
> +
```suggestion
```

2020-08-25 12:58 UTC, RobinSiep approved these changes

2020-08-25 12:58 UTC, merged