Ap 41 logout
thecoderstudio/apollo-web pull request #7
Opened 2020-07-08 10:41 UTC by rikvanderwerf

## Code R Ticket
_Please provide a link to the Code R Jira ticket if applicable_

<https://partypeak.atlassian.net/browse/AP-41>

## Description
Added a navbar that shows an options wheel with a logout function. 

![image](https://user-images.githubusercontent.com/5989836/86909041-cca51180-c117-11ea-8d3c-c15710dd25b6.png)
![image](https://user-images.githubusercontent.com/5989836/86909068-d6c71000-c117-11ea-990c-f9bb1adde046.png)

## Dependencies
_Are there any dependencies in relation to pull requests in other Apollo repositories? If so please provide links to these pull requests_

*

## Additional notes
Added `babel-plugin-styled-components` so that when enzyme.mount is called. The elements have the name of the styled component without having to set the displayName for every styled component. This way they can be found using de enzyme.find function.

Also the reason for `this.props.collapsed.soString` in the `NavBar.jsx line 105` is discussed here https://github.com/styled-components/styled-components/issues/1198.

2020-07-08 11:34 UTC, rikvanderwerf commented
For the codacy comment: `navBarReducer(undefined, {})`. I copied that from the auth reducer. Don't really know a way to do it any different.

2020-07-08 12:56 UTC, RobinSiep requested changes
Lots of whitespaces after lines, example:
![image](https://user-images.githubusercontent.com/5303534/86918391-ec900180-c126-11ea-906e-6f50aae81269.png)

As mentioned, I've glanced over the tests for now. This includes the redux tests also because the questionability of using redux will probably cause big changes.

2020-07-08 12:56 UTC, RobinSiep commented on package.json
> +    "@fortawesome/react-fontawesome": "^0.1.11",
I'm not sure if this is worth the overhead. Font awesome is also popular enough that using the CDN backed dependency is probably worth it over the con of third party network dependency.

The react lib isn't event and a 1.0 version yet.

2020-07-08 12:56 UTC, RobinSiep commented on src/actions/navbar.js
> +export const toggleOptions = (collapsed) => (
Why does this functionality use Redux? In what usecase would we want the options toggled outside of the responsible component? (currently the nav bar)

In the best case this is some heavy future proofing but the overhead that implementing something with Redux provides is not worth it. If we ever need to toggle the options from outside of its reasonable context we can always refactor.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +const Icon = styled(FontAwesomeIcon)`
What's the thought process behind always using an icon instead of, for example, only on mobile? It's 1 option and there's plenty of screen real estate on tablet and desktop devices. Is it some kind of future proofing? Because currently I'm not sure why the extra click is needed.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +  grid-template-columns: 1fr [options] 300px;
Wouldn't a max width of `300px` on the child give you the effect you want without having to do anything mobile specific?

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +  max-height: 50px;
This being closely tied with the `NavigationBar` height is a code smell. If one changes the other won't necessarily be updated since it's a hidden coupling.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +  -webkit-transform: ${props => props.collapsed === 'true' ? 'rotate(0)' : 'rotate(90deg)'};
Wouldn't
```
-webkit-transform: ${props => props.collapsed ? 'rotate(0)' : 'rotate(90deg)'};
...
```

suffice?

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +import React from 'react';
Some intent behind the import ordering would be nice. I usually do react followed by other third party libs followed by ours.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +  box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
This seems to be a duplication of the card shadow which means you should either abstract the shadow property or extend the card.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +    background-color: ${props => props.theme.darkWhite};
Does this work for you? It doesn't seem to work for me.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +
```suggestion
```

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +    dispatch(toggleOptionsAction(true));
`toggleOptionsAction(true)` doesn't read well. It's not a toggle if you supply a state you want it to be in. Toggle wouldn't take an argument. `setOptionsCollapsed(true)` would make sense.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +    this.state = { collapsed: true };
Seemingly unused.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +class NavBar extends React.Component {
```suggestion
class NavBar extends React.PureComponent {
```

2020-07-08 12:56 UTC, RobinSiep commented on src/pages/Dashboard.jsx
> +    <NavBar></NavBar>
```suggestion
    <NavBar />
```

2020-07-08 12:56 UTC, RobinSiep commented on src/pages/Dashboard.jsx
> +import media from '../util/media';
```suggestion
```

2020-07-08 12:56 UTC, RobinSiep commented on src/pages/Dashboard.jsx
> +import NavBar from '../components/NavBar';
Put under react import statement please

2020-07-08 12:56 UTC, RobinSiep commented on src/pages/Dashboard.jsx
> +
```suggestion
```

2020-07-08 12:56 UTC, RobinSiep commented on tests/components/navbar.test.js
> +import Enzyme, { mount, shallow } from 'enzyme';
What's the reason behind Enzyme being used instead of snapshot testing? The reason its added to the project and used in the terminal test is because `xtermjs` needs an actual DOM (due to interaction with parent node on open).

Instead of testing whether certain actions get called you'd expect to assert whether the new snapshot matches what you'd expect on option toggle and logout.

2020-07-08 12:56 UTC, RobinSiep commented on tests/components/navbar.test.js
> +    await waitForExpect(() => {
Is this needed? I don't see any async functionality in the implementation code.

2020-07-08 12:56 UTC, RobinSiep commented on tests/components/navbar.test.js
> +import waitForExpect from 'wait-for-expect';
As mentioned above, some reasoning behind the import ordering would be nice for readability sake.

2020-07-08 12:56 UTC, RobinSiep commented on tests/components/navbar.test.js
> +
```suggestion
```

2020-07-08 12:56 UTC, RobinSiep commented on tests/components/navbar.test.js
> +import Enzyme, { mount, shallow } from 'enzyme';
I'll skip the review of these tests for now until there's more clarity whether they're going to change.

2020-07-08 12:56 UTC, RobinSiep commented on tests/pages/Dashboard.test.jsx
> +import configureStore from 'redux-mock-store';
Import order.

2020-07-08 12:56 UTC, RobinSiep commented on src/components/NavBar.jsx
> +  state => ({ authenticated: state.authenticated, collapsed: state.collapsed })
I don't see the authenticated property being used anywhere (nor should it, not this components concern).

2020-07-08 13:15 UTC, RobinSiep commented
> Also the reason for this.props.collapsed.soString in the NavBar.jsx line 105 is discussed here styled-components/styled-components#1198.

The proper solution for that problem seems to be to filter out the property instead of passing it along to the overridden component. Styled components can’t possibly know what shouldn’t be passed along themselves.

2020-07-09 08:19 UTC, rikvanderwerf commented on tests/components/navbar.test.js
> +import Enzyme, { mount, shallow } from 'enzyme';
> Instead of testing whether certain actions get called you'd expect to assert whether the new snapshot matches what you'd expect on option toggle and logout. 

Can you maybe write an example on how to do this now i've removed the toggle functionality and only the logout remains?. Like do you mean calling the action yourself and then checking the snapshot?

2020-07-09 08:28 UTC, RobinSiep commented on tests/components/navbar.test.js
> +import Enzyme, { mount, shallow } from 'enzyme';
https://jestjs.io/docs/en/tutorial-react#snapshot-testing

So you'd basically call the `onClick()` of your component similar to how they call the `onMouseEnter()` and `onMouseEnter()` of their component (which is on the `<a />` tag, not to be confused with `_onMouseEnter()` and `_onMouseLeave()`). You may have to go a little deeper in your tree first if the tag holding the probs is not the root tag.

2020-07-09 11:12 UTC, RobinSiep requested changes

2020-07-09 11:12 UTC, robinsiep commented on src/components/NavBar.jsx
> +  grid-template-columns: 1fr [logout] 100px;
Is the `100px` still needed if the `max-width` of the child is 100px? Like this it won't ever be anything _other_ than `100px` so then the `width` of the child might as well be `100px` instead of the `max-width` right?

2020-07-09 11:12 UTC, RobinSiep commented on tests/components/navbar.test.js
> +describe('login', () => {
```suggestion
describe('nav bar', () => {
```

2020-07-09 11:12 UTC, RobinSiep commented on src/components/NavBar.jsx
> +  &:hover {
I don't think this is necessary. `Logout` is a `OutlinedButton` which extends `Button` which implements cursor functionality.

2020-07-09 11:12 UTC, RobinSiep commented on tests/components/navbar.test.js
> +    spy = jest.spyOn(store, 'dispatch');
spy unused I think. I'd use the spy in `handles successful logout` just for sanity sake since the snapshot won't really change upon logout so you'll want to assert this "side effect".

2020-07-09 11:12 UTC, RobinSiep commented on tests/components/navbar.test.js
> +  it("handles successful logout", async () => {
No need to be async I think.

2020-07-09 11:12 UTC, RobinSiep commented on tests/components/navbar.test.js
> +import React from 'react';
Rename to `NavBar.text.js` like the other test files.

2020-07-09 12:03 UTC, RobinSiep requested changes

2020-07-09 12:03 UTC, robinsiep commented on src/components/NavBar.jsx
> +  width: 100px;
Meaning you can now remove the column constraint.

2020-07-09 12:03 UTC, RobinSiep commented on tests/components/navbar.test.js
> +    waitForExpect(() => {
```suggestion
    await waitForExpect(() => {
```

2020-07-09 12:03 UTC, RobinSiep commented on tests/components/navbar.test.js
> +  it("handles successful logout", () => {
```suggestion
  it("handles successful logout", async () => {
```

2020-07-09 12:03 UTC, RobinSiep commented on tests/components/navbar.test.js
> +import React from 'react';
Still needs a rename, according to Github at least.

2020-07-09 14:01 UTC, RobinSiep requested changes

2020-07-09 14:01 UTC, RobinSiep commented on tests/components/navbar.test.js
> +import React from 'react';
> Rename to NavBar.test.js like the other test files.
---
> Still needs a rename, according to Github at least.

Stil still shows up as `navbar.test.js` on Github.

2020-07-09 14:51 UTC, rikvanderwerf commented
ffs github, renamed it twice already 😂

2020-07-09 14:58 UTC, RobinSiep commented
@rikvanderwerf test kaput

2020-07-09 15:08 UTC, RobinSiep approved these changes

2020-07-09 15:10 UTC, RobinSiep commented
I just noticed it had a typo that said "logout" whereas we use "log in" elsewhere so I quickly fixed this. Just waiting for test now. I didn't do a mobile check but I assume the button looks alright there too for now.

2020-07-09 15:10 UTC, merged